(PC-4127): Fix Discovery Geolocation
pass-culture/pass-culture-browser pull request #1783
Opened 2020-08-28 17:02 UTC by DanielBaudry

2020-08-31 15:31 UTC, atusithi requested changes

2020-08-31 15:31 UTC, atusithi commented on src/components/pages/discovery/DiscoveryContainer.js
> +  )
```suggestion
  return (
    coordinates && coordinates.latitude && coordinates.longitude
  )
```
ça fonctionne ça par hasard ?

2020-08-31 15:31 UTC, atusithi commented on src/components/pages/discovery/DiscoveryContainer.js
> +      navigator.geolocation.getCurrentPosition(
La geolocation est déjà dispo dans le store normalement. Pourquoi avoir besoin de passer par navigator ?

2020-08-31 15:31 UTC, atusithi commented on src/components/pages/discovery/DiscoveryContainer.js
> +    }
Factoriser pour faire un seul appel avec coordinates

2020-09-02 09:34 UTC, atusithi requested changes

2020-09-02 09:34 UTC, atusithi commented on src/components/pages/discovery/__specs__/DiscoveryContainer.spec.js
> +      it('should load the recommendations with page equals 1 when no current recommendation', async () => {
Il faudrait renommer le test pour le rendre cohérent avec ce qu'il fait réellement. "should load recommendations without using user geolocation when it is denied"

2020-09-02 09:34 UTC, atusithi commented on src/components/pages/discovery/__specs__/DiscoveryContainer.spec.js
> +      it('should load the recommendations with page equals 2 when current recommendation is a valid one attached to an offer', async () => {
Il faudrait renommer le test pour le rendre cohérent avec ce qu'il fait réellement. "should load recommendations without user geolocation when it is denied"

2020-09-02 09:34 UTC, atusithi commented on src/components/pages/discovery/__specs__/DiscoveryContainer.spec.js
> +      it('should make request with given geolocation to API', async () => {
```suggestion
      it('should make request to API with user geolocation when user geolocation is granted', async () => {
```

2020-09-02 09:34 UTC, atusithi commented on src/components/pages/discovery/__specs__/DiscoveryContainer.spec.js
> +      it('should load the recommendations when user is geolocated', async () => {
```suggestion
      it(''should load recommendations using user geolocation when user geolocation is granted'', async () => {
```

2020-09-02 09:34 UTC, atusithi commented on src/components/pages/discovery/__specs__/DiscoveryContainer.spec.js
> +      it('should load the recommendations when user is not geolocated', async () => {
c'est pas le même test que le précédent ?

2020-09-02 13:46 UTC, atusithi approved these changes

2020-09-02 13:46 UTC, merged

2020-10-12 14:19 UTC, victorenaud commented on src/components/pages/discovery/DiscoveryContainer.js
> +      navigator.geolocation.getCurrentPosition(
Parfois ça ne fonctionne pas et il faut forcer la récupération