(MOB): Prettier Eslint
pass-culture/pass-culture-browser pull request #1809
Opened 2020-09-17 10:25 UTC by apibrac

2020-09-17 12:18 UTC, NerOcrO requested changes

2020-09-17 12:18 UTC, NerOcrO commented on .eslintrc
> +    "react/function-component-definition":  [2, { "namedComponents": "arrow-function" }],
Je ne vois pas l'intérêt de cette règle ?
De plus, elle ajoute une vingtaine de warning de ce type quand je lance l'app :
`./src/components/layout/Recto/Recto.jsx
  Line 1:  Definition for rule 'react/function-component-definition' was not found  react/function-component-definition`

2020-09-17 12:18 UTC, NerOcrO commented on package.json
> +    "*.{js,jsx,md,css,scss,html}": [
Il manque la partie d'optimisation des SVG.

2020-09-17 12:18 UTC, NerOcrO commented on src/components/pages/typeform/__specs__/Typeform.spec.jsx
> +          push: function() {
Il faut que je puisse mettre une arrow function ici.

2020-09-17 12:21 UTC, victorenaud commented on src/components/pages/typeform/__specs__/Typeform.spec.jsx
> +          push: function() {
On peut désactiver la règle no arrow function in props
Tu veux ?

2020-09-17 12:22 UTC, victorenaud commented on .eslintrc
> +    "react/function-component-definition":  [2, { "namedComponents": "arrow-function" }],
Cette règle permet de lui dire qu'on accepte les composants fonctionnels en arrow function
Sinon il veut les passer en function, et là c'est toi qui ne veut pas :P

2020-09-17 13:49 UTC, NerOcrO commented on .eslintrc
> +    "react/function-component-definition":  [2, { "namedComponents": "arrow-function" }],
Dire à qui ?
Parce qu'avant, on pouvait faire desarrow functions partout sans problème.
Moi, je veux qu'on est la possibilité de mettre en arrow function tout le temps.

2020-09-17 13:51 UTC, NerOcrO commented on src/components/pages/typeform/__specs__/Typeform.spec.jsx
> +          push: function() {
J'aimerai surtout comprendre pourquoi il y a cette régression alors que ça marchait bien avant et c'est le seul cas où il transforme en function basique.

2020-09-17 15:28 UTC, apibrac commented on .eslintrc
> +    "react/function-component-definition":  [2, { "namedComponents": "arrow-function" }],
Le plugin `"plugin:react/all"` met cette règle à "function-declaration" par défault, ce qui force les composant à être de ce format : 
```javascript
function Component (props) {
  return <div />;
}
```
La on l'a mise à arrow-function pour qu'on puisse faire des arrow-function (et que ça du coup)

Au choix : 
- soit on met cette règle à off pour qu'on fasse les deux
- soit on enlève cette ligne mais alors pas de arrow-function
- soit on met la règle à arrow-function

You choose j'ai aucun avis

2020-09-17 15:42 UTC, apibrac commented on src/components/pages/typeform/__specs__/Typeform.spec.jsx
> +          push: function() {
Pareil que l'autre cas, le plugin react all nous force des functions component par default
On l'avait pas mi en arrow-function dans le cas "unamedComponent"
C'est chose faite dans le prochain commit :)

2020-09-17 16:55 UTC, NerOcrO approved these changes

2020-09-17 16:55 UTC, NerOcrO commented on src/utils/fetch-normalize-data/reducers/data/actionCreators.js
> +  result: function() {
Il manque celui-ci.

2020-09-18 07:31 UTC, NerOcrO commented on package.json
> +    "lint-staged": "10.3.0",
Il faut le petit chapeau devant.

2020-09-18 08:11 UTC, NerOcrO requested changes

2020-09-18 08:11 UTC, NerOcrO commented on package.json
> +    "prettier": "^2.1.2",
Il doit être mis dans les devdependencies

2020-09-18 12:33 UTC, NerOcrO approved these changes

2020-09-18 12:52 UTC, merged