(PC-6256) Post email to cloud function in IdCheckDisabled mode
pass-culture/pass-culture-browser pull request #1894
Opened 2021-01-18 13:48 UTC by viconnex

2021-01-18 13:58 UTC, Akhilian requested changes

2021-01-18 13:58 UTC, Akhilian commented on src/components/pages/create-account/IdCheckDisabled/IdCheckDisabled.jsx
> +          'https://europe-west1-passculture-metier-ehp.cloudfunctions.net/fallback-store-email',
Variable d'environnement ?

2021-01-18 13:58 UTC, Akhilian commented on src/components/pages/create-account/IdCheckDisabled/IdCheckDisabled.jsx
> +    async event => {
Je veux bien un test sur l'envoi de mail (vérifier que la saisie est OK et l'envoi contient correctement l'email), et sur les changements d'état ("mail envoyé") et le cas d'erreur si le fetch POST échoue 😬

2021-01-18 14:55 UTC, viconnex commented on src/components/pages/create-account/IdCheckDisabled/IdCheckDisabled.jsx
> +          'https://europe-west1-passculture-metier-ehp.cloudfunctions.net/fallback-store-email',
pas sûr que ça dépende de l'environnement

2021-01-19 08:22 UTC, Akhilian approved these changes

2021-01-19 09:08 UTC, merged