(PC-4847) Pass (unhumanized) user id as a query param for typeform in addition of dynamic UUID
pass-culture/pass-culture-browser pull request #1954
Opened 2021-03-10 15:51 UTC by BenStirrup

Lien ticket Jira : https://passculture.atlassian.net/browse/PC-4847

Test unitaires mis à jours : 👍🏻

2021-03-10 16:39 UTC, apibrac commented on src/components/pages/typeform/Typeform.jsx
> +    const queryParams = queryString.stringify({ userId: this.props.user.id })
Est ce qu'il ne faudrait pas changer la clé pour identifier le changement dans les données ?

Ou juste rajouter un boolean si le changement de clé a un impact ailleurs ?

2021-03-10 16:41 UTC, apibrac requested changes
Mieux vaut utiliser les vrais id que le humanized

2021-03-10 17:11 UTC, BenStirrup commented on src/components/pages/typeform/Typeform.jsx
> +    const queryParams = queryString.stringify({ userId: this.props.user.id })
C'est une bonne question.
Faudrait que je m'entretienne avec une personne qui utilise cette correspondance typeform <> user.
L'équipe data ?

2021-03-10 17:12 UTC, BenStirrup commented
Ok pour utiliser les vrais (déshumanisés) ids des utilisateurs via `dehumanizeId(user.id)`.

2021-03-10 17:28 UTC, apibrac commented on src/components/pages/typeform/Typeform.jsx
> +    const queryParams = queryString.stringify({ userId: this.props.user.id })
Oui c'est l'équipe data

2021-03-10 17:28 UTC, apibrac commented
Pas mieux de modifier beneficiaries current ? ça semble mieux sur le long terme

2021-03-11 15:33 UTC, BenStirrup commented
On a une nouvelle propriété `pk` sur l'objet `User` :) 
La route backend a été modifié

2021-03-11 17:34 UTC, apibrac commented on src/components/pages/typeform/TypeformContainer.js
> +  return { culturalSurveyId: uuid(), userId: user.pk }
le mapStateToProps est potentiellement éxécuté plusieurs fois pendans la vie du composant, donc tu vas te retrouver avec un uuid qui change
est ce que c'est pas un peu error prone ?

ça semble mieux de le remettre dans le composant, d'autant qu'on tend à avoir de moins en moins de chose dans ces containers dans nos autres repos

2021-03-12 08:28 UTC, BenStirrup commented on src/components/pages/typeform/TypeformContainer.js
> +  return { culturalSurveyId: uuid(), userId: user.pk }
Yes bien vu, j'ai mis la génération du UUID dans le constructor (comme avant).
Cela fait trop longtemps que je n'ai pas utilisé Redux ;)

2021-03-12 09:01 UTC, apibrac approved these changes

2021-03-12 09:08 UTC, merged